name: Publish to NPM
on:
  # push:
  #   tags: ["v*"]
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Angular CLI
        run: npm install -g @angular/cli @angular/core
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build project
        run: ng build --configuration production --project=ngx-authp-service
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/ngx-authp-service/package.json
          access: public
